# Generated by Django 4.2.30 on 2026-10-02 10:23

from django.db import migrations, models
import django.db.models.deletion


def add_initial_participants(apps, schema_editor):
    Participant = apps.get_model('circle', 'Participant')
    for name in ['Gilbert', 'Benitha', 'Paradi', 'Loic', 'Mugisha', 'Dosite']:
        Participant.objects.using(schema_editor.connection.alias).get_or_create(name=name)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chooser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice_made', to='circle.participant')),
                ('selected', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by', to='circle.participant')),
            ],
        ),
        migrations.RunPython(add_initial_participants, migrations.RunPython.noop),
    ]
